services:
  rabbitmq:
    image: 'rabbitmq:3.11-management'
    ports:
      - "15673:15672"  # Management UI
      - "5673:5672"    # AMQP protocol
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
